### ISSUE TITLE
大佬，为啥没效果？

### ISSUE THREAD

**Issue by DevXue** [zhchbin/WeChatAirKiss#6]
我把Demo跑起来，输入密码后  准备连接硬件设备了，  可是总是没反应  最后就 提示超时了 TimeOut，请问我该怎么做呢？  我对这个不太了解！  望指点！谢谢

**Comment by maitao** [comment]
英文可以，中文不行，请问这个如何解决呢？中文WIFI名称，报这个错：
java.lang.IllegalArgumentException: illegal length or offset
06-19 14:55:50.627 7397-7619/me.zhchbin.arikiss W/System.err:     at java.net.DatagramPacket.setData(DatagramPacket.java:283)
06-19 14:55:50.627 7397-7619/me.zhchbin.arikiss W/System.err:     at java.net.DatagramPacket.<init>(DatagramPacket.java:125)
06-19 14:55:50.628 7397-7619/me.zhchbin.arikiss W/System.err:     at java.net.DatagramPacket.<init>(DatagramPacket.java:177)
06-19 14:55:50.629 7397-7619/me.zhchbin.arikiss W/System.err:     at me.zhchbin.airkiss.MainActivity$AirKissTask.sendPacketAndSleep(MainActivity.java:138)
06-19 14:55:50.629 7397-7619/me.zhchbin.arikiss W/System.err:     at me.zhchbin.airkiss.MainActivity$AirKissTask.doInBackground(MainActivity.java:158)
06-19 14:55:50.630 7397-7619/me.zhchbin.arikiss W/System.err:     at me.zhchbin.airkiss.MainActivity$AirKissTask.doInBackground(MainActivity.java:68)

**Comment by ilivein** [comment]
@maitao 你这问题是中文时候，生成的待发送的数据出现负的值，而airkiss的数据以length字段作为数据传输载体，length字段不能为负数，所以抛了异常。 [可以看一下这个工程，里面改的AIrkissEncoder类做了修改，支持中文WiFi配网，希望对你有帮助。](https://github.com/ilivein/AndroidAirKis)
